name: Deploy release to server

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/ReadMe.md'

jobs:
  deploy-release:
  
    runs-on: ubuntu-latest
    environment: main
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Copy A5 release file to server
        uses: appleboy/scp-action@v1.0.0
        with:
          source: "./release/songbook.pdf"
          target: ${{ secrets.SSH_SERVER_PATH }}
          host: ${{ secrets.SSH_SERVER_HOST }}
          port: ${{ secrets.SSH_SERVER_PORT }}
          username: ${{ secrets.SSH_SERVER_USER }}
          key: ${{ secrets.SSH_SERVER_KEY }}
          passphrase: ${{ secrets.SSH_SERVER_PASSPHRASE }}
          strip_components: 2
      - name: Copy A4 release file to server
        uses: appleboy/scp-action@v1.0.0
        with:
          source: "./release/songbook_A4.pdf"
          target: ${{ secrets.SSH_SERVER_PATH }}
          host: ${{ secrets.SSH_SERVER_HOST }}
          port: ${{ secrets.SSH_SERVER_PORT }}
          username: ${{ secrets.SSH_SERVER_USER }}
          key: ${{ secrets.SSH_SERVER_KEY }}
          passphrase: ${{ secrets.SSH_SERVER_PASSPHRASE }}
          strip_components: 2
