name: Deploy release to server

permissions:
  id-token: write
  contents: read
  checks: write

on:
  push:
    branches: [ "master" ]

jobs:
  deploy-release:
  
    runs-on: ubuntu-latest
    environment: master
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Copy release file to server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./Songbook/release/songbook.pdf
          remote: ${{ secrets.SSH_SERVER_PATH }}/songbook.pdf
          host: ${{ secrets.SSH_SERVER_HOST }}
          port: ${{ secrets.SSH_SERVER_PORT }}
          username: ${{ secrets.SSH_SERVER_USER }}
          privateKey : ${{ secrets.SSH_SERVER_KEY }}
          passphrase: ${{ secrets.SSH_SERVER_PASSPHRASE }}