name: Deploy release to server

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-release:
  
    runs-on: ubuntu-latest
    environment: main
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Copy release file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          source: "./release/songbook.pdf"
          target: ${{ secrets.SSH_SERVER_PATH }}
          host: ${{ secrets.SSH_SERVER_HOST }}
          port: ${{ secrets.SSH_SERVER_PORT }}
          username: ${{ secrets.SSH_SERVER_USER }}
          key: ${{ secrets.SSH_SERVER_KEY }}
          passphrase: ${{ secrets.SSH_SERVER_PASSPHRASE }}
